"""empty message

Revision ID: 473f0bf9dea0
Revises: 70e792daf799
Create Date: 2017-10-20 16:20:24.818509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '473f0bf9dea0'
down_revision = '70e792daf799'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('admin', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'admin')
    # ### end Alembic commands ###
